# -*- coding: utf-8 -*-
"""titanic-ml-project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T2qxPoxLFREJg2gJ45CmT9yZb096lw66
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

train.head()

train.info()

train.isnull().sum()

train['Age'] = train['Age'].fillna(train['Age'].median())

train.isnull().sum()

train['FamilySize'] = train['SibSp'] + train['Parch'] + 1
test['FamilySize'] = test['SibSp'] + test['Parch'] + 1

train['IsAlone'] = (train['FamilySize'] == 1).astype(int)
test['IsAlone'] = (test['FamilySize'] == 1).astype(int)

train = train.drop(columns=['Cabin'])
test = test.drop(columns=['Cabin'])

train = train.drop(columns=['Name'])
test = test.drop(columns=['Name'])

train = train.drop(columns=['Ticket'])
test = test.drop(columns=['Ticket'])

train.isnull().sum()

from sklearn.preprocessing import LabelEncoder

train['Sex'] = le.fit_transform(train['Sex'])
test['Sex'] = le.transform(test['Sex'])

train = pd.get_dummies(train, columns=['Embarked'], drop_first=True)
test = pd.get_dummies(test, columns=['Embarked'], drop_first=True)

test = test.reindex(columns=train.columns.drop('Survived'), fill_value=0)

train.info()

train['Embarked_Q'] = train['Embarked_Q'].astype(int)
train['Embarked_S'] = train['Embarked_S'].astype(int)

test['Embarked_Q'] = test['Embarked_Q'].astype(int)
test['Embarked_S'] = test['Embarked_S'].astype(int)

train.info()

from sklearn.model_selection import train_test_split

X = train.drop(['Survived', 'PassengerId'], axis=1)
y=train.Survived

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

X_train.head()

y_train.head()

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, precision_score, f1_score, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

model.fit(X, y)

test_X = test.drop('PassengerId', axis=1)
predictions = model.predict(test_X)

submission = pd.DataFrame({
    "PassengerId": test["PassengerId"],
    "Survived": predictions
})

submission.to_csv("submission.csv", index=False)

import os
os.listdir()

from google.colab import files
files.download("submission.csv")